image: rust:1.45.0

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - cargo test

build:
  stage: build
  artifacts:
    paths:
      - target/release/podcasts
    expire_in: 1 day
  script:
    - cargo build --release
