image: rust:1.45.0

stages:
  - test
  - publish

test:
  stage: test
  script:
    - cargo test

publish:
  stage: publish
  when: manual
  only:
    - master
  script:
    cargo publish --token "$CARGO_API_KEY"
