image: rust:1.45.0

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - cargo test

publish:
  stage: publish
  when: manual
  only:
    - master
  before_script:
    - cargo login $CARGO_API_KEY
  script:
    cargo publish
